global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Pushgateway for custom metrics
  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]
    scrape_interval: 5s
    honor_labels: true

  # Custom application metrics
  - job_name: "custom-metrics"
    static_configs:
      - targets: ["pushgateway:9091"]
    metrics_path: /metrics
    scrape_interval: 10s
